name: piece_table
description: Fast piece table implementation using custom splay tree with cursor support
version: 1.0.2
homepage: https://github.com/buttercrab/piece_table

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  benchmark_harness: ^1.0.5
  random_string: ^2.0.1
